name: sphinx

on:
  push:
    branches:
      - main

jobs:
 run_sphinx_html:
   runs-on: ubuntu-latest
   steps:
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: clone sources
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Upgrade pip, install requirements, build docs
        run: |
          pip install --upgrade pip
          pip install -r ./docs/requirements.txt
          cd docs
          make html

      - uses: actions/upload-artifact@v4
        with:
          name: DocumentationHTML
          path: docs/_build/html/

      - name: clone gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          clean: false
          path: gh-pages

      - name: push to gh-pages
        run: |
          cp -r docs/_build/html/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.SPHINX_ACTION_ACCESS_TOKEN }}

 run_rinoh_pdf:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - name: run rinoh
       run: |
         pip install -r docs/requirements.txt
         cd docs
         sphinx-build -b rinoh . _build/rinoh
     - uses: actions/upload-artifact@v4
       with:
         name: RinohPdf
         path: docs/_build/rinoh/
